/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedbackRsp } from '../models/feedback-rsp';
export interface PageDtoFeedbackRsp {
  content?: Array<FeedbackRsp>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
