/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedBookRsp } from '../models/borrowed-book-rsp';
export interface PageDtoBorrowedBookRsp {
  content?: Array<BorrowedBookRsp>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
